#
# jenkins.yaml
#
apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: jenkins
spec:
  # chart identifies a matching chart from a .tgz
  chart:
    name: jenkins
    chartVersion: 13.4.28
  optionalValues:
  - when: 'repl{{ eq Distribution "embedded-cluster" }}'
    recursiveMerge: false
    values:
      service:
        type: NodePort
        nodePorts:
          http: "33000"